### ISSUE TITLE
Typo in scheduler concept

### ISSUE THREAD

**Issue by dietmarkuehl** [atomgalaxy/review-executor-sendrecv#6]
Not really a discussion but I think there is a typo in the `scheduler` concept (2.2.8):

    template<class S>
    concept scheduler =
        copy_constructible<remove_cvref_t<S>> &&
        equality_comparable<remove_cvref_t<S>> &&
        requires(E&& e) {
          execution::schedule((E&&)e);
        };

The `requires` clause should use `S` instead of `E`. This isn't really a discussion.

**Comment by ericniebler** [comment]
Has been noted and already fixed: https://github.com/executors/executors/issues/476

Thanks!
